networks:
  internal: null
  public: null

services:
  yanagi-autopatch-server:
    image: ghcr.io/garnetsunset/yanagi-autopatch-server:latest
    networks:
      - public
      - internal
    ports:
      - '10000:10000'
    restart: unless-stopped

  yanagi-dispatch-server:
    depends_on:
      - yanagi-autopatch-server
    image: ghcr.io/garnetsunset/yanagi-dispatch-server:latest
    networks:
      - public
      - internal
    ports:
      - '10002:10002'
    restart: unless-stopped

  yanagi-game-server:
    depends_on:
      - yanagi-autopatch-server
    image: ghcr.io/garnetsunset/yanagi-game-server:latest
    networks:
      - internal
    ports:
      - '10101:10101'
    restart: unless-stopped

  yanagi-gate-server:
    depends_on:
      - yanagi-autopatch-server
    image: ghcr.io/garnetsunset/yanagi-gate-server:latest
    networks:
      - public
      - internal
    ports:
      - 20501:20501/udp
    restart: unless-stopped

  yanagi-sdk-server:
    depends_on:
      - yanagi-surrealdb
    image: ghcr.io/garnetsunset/yanagi-sdk-server:latest
    network_mode: service:yanagi-surrealdb
    restart: unless-stopped

  yanagi-surrealdb:
    command: start --user root --pass root file:///data/surrealdb_data
    container_name: surrealdb
    image: surrealdb/surrealdb:latest
    networks:
      - internal
    ports:
      - "8000:8000"
      - 10001:10001
    restart: unless-stopped
    user: '1000:1000'
    volumes:
      - surrealdb_data:/data/surrealdb_data

volumes:
  surrealdb_data:
    driver: local
