name: Build and Publish Docker Images

on:
  push:
    branches:
      - master
    paths:
      - '**/Dockerfile'
      - '**/Cargo.lock'
      - '**/Cargo.toml'
      - 'crates/**'
      - 'autopatch/**'
  pull_request:
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]
        service: [yanagi-sdk-server, yanagi-autopatch-server, yanagi-dispatch-server, yanagi-gate-server, yanagi-game-server]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: "linux/amd64,linux/arm64"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          use: true

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Timestamp
        id: get_time
        run: echo "timestamp=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Build and Push Multi-Platform Images
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            SERVICE=${{ matrix.service }}
          platforms: linux/amd64,linux/arm64
          push: true
          attests: false
          tags: |
            ghcr.io/garnetsunset/${{ matrix.service }}:latest
            ghcr.io/garnetsunset/${{ matrix.service }}:${{ env.timestamp }}
